sudo: required
language: java

dist: precise
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
 - docker

cache:
  directories:
    - frontend/node_modules
    - $HOME/.m2

before_install:
  - export TZ=Europe/Zurich
install: mvn clean compile -Dmaven.javadoc.skip=true -B -V
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: mvn clean package -B -V

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t "guggero/cloudcoins:latest" docker/;
      docker build -t "guggero/cloudcoins:$TRAVIS_BUILD_NUMBER" docker/;
      docker push "guggero/cloudcoins:latest";
      docker push "guggero/cloudcoins:$TRAVIS_BUILD_NUMBER";
    fi